### ISSUE TITLE
npm package doesnt contain dist folder

### ISSUE THREAD

**Issue by VinodVitana** [merge-api/merge-hris-node#15]
Hi,

Looks like your package was not built before pushing to npm. I dont see dist folder in the node_modules folder

![image](https://user-images.githubusercontent.com/86854769/124514431-9ff30b00-ddfa-11eb-92a7-d80e07d511be.png)

Thanks.

**Comment by haletothewood** [comment]
Seconded!

**Comment by hmafzal** [comment]
This SDK is deprecated and we no longer maintain it. We'd encourage you to migrate to our [newer multicategory SDKs](https://help.merge.dev/en/articles/7992820-using-merge-sdks) for better functionality, latest API updates and faster support.
