### ISSUE TITLE
`request` is deprecated, and has a security vulnerability, any plans to migrate away?

### ISSUE THREAD

**Issue by chrishutchinson** [merge-api/merge-hris-node#41]
As per the title, `request` has been [deprecated for some time](https://github.com/request/request/issues/3142), and has a [dependency on a vulnerable version of `qs`](https://github.com/request/request/issues/3411).

Do you have plans to migrate away from `request` towards a more modern alternative?

**Comment by imaginetheheadline** [comment]
Come on, Merge, at least comment on this issue please. CC: @dan-merge @leewang0 @eltonkl @Gallinaryoso who is responsible here?

**Comment by hmafzal** [comment]
This SDK is deprecated and we no longer maintain it. We'd encourage you to migrate to our [newer multicategory SDKs](https://help.merge.dev/en/articles/7992820-using-merge-sdks) for better functionality, latest API updates and faster support.

The newer SDK does not use the `request` package.
